sudo: false
language: python
python:
- "2.7"
- "3.4"
addons:
  apt:
    packages:
    - libjpeg-turbo8-dev
    - libavcodec-dev
    - libswscale-dev
install: "pip install -r requirements.txt"
script:
  - python setup.py build_ext --inplace
  - python setup.py test
deploy:
  provider: pypi
  user: hakanardo
  password:
    secure: LA16LJyigOhZPqBulP/jT0DbM8cDnGma5y/7ldiHpEJTuKUYQ9VJSKDnxYXPRnTyWtQT2VioQtqMES3m8djBsrI8mm85heJUDI67EyRl7g/MEljBiSeida2VTwlY4U5INBuCyijQ5j52U1C2SOKksnBIaO7yh2MuOL4M/nMnIWI=
  on:
    branch: stable
