name: test

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        python-version: ['3.10']
        include:
          - python-version: '3.10'
            pep-425-tag: 'cp310-cp310'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 twine
        pip install -r requirements.txt
    # - name: Lint with flake8 for syntax errors
    #   run: |
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.5.0-manylinux_2_24_x86_64
      with:
        python-versions: ${{ matrix.pep-425-tag }}
        build-requirements: 'cffi numpy'
        system-packages: 'libjpeg62-turbo-dev libavcodec-dev libswscale-dev libffi-dev'
    - name: Install wheel
      run: pip install vi3o --no-index -f dist/
    - name: Install test dependencies
      run: |
        sudo apt-get --yes install ffmpeg
        pip install pytest
        pip install -r requirements.txt
    - name: Test wheel
      run: |
        cp -r test ~
        cd ~/test
        HEADLESS=1 py.test
    - name: Publish wheels to PyPI
      if: github.event_name == 'release' && matrix.os == 'ubuntu-22.04'
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*-manylinux*.whl        